# -*- coding: utf-8 -*-
"""Sentiment_Analysis_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNLjdvaTo1HUZh8lXTBnoYXvSM-0Otko
"""

!pip install transformers torch

""" Load the Sentiment Analysis Model"""

from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")

"""Create a Function for Sentiment Analysis"""

def analyze_sentiment(text):
    if text.strip() == "":
        return "Please enter some text to analyze!"

    # Perform sentiment analysis
    result = sentiment_pipeline(text)[0]
    sentiment = result['label']
    confidence = result['score']

    return f"Sentiment: {sentiment}\nConfidence: {confidence:.2f}"

"""Add User Input and Display Results"""

# Get user input
user_input = input("Enter some text to analyze: ")

# Analyze the sentiment and display the result
result = analyze_sentiment(user_input)
print(result)



"""Analyze Multiple Sentences"""

def analyze_multiple_sentences(texts):
    results = sentiment_pipeline(texts)
    for i, result in enumerate(results):
        print(f"Text {i+1}: {result['label']} (Confidence: {result['score']:.2f})")

texts = [
    "I love this project!",
    "This is the worst experience ever.",
    "It's okay, not great."
]
analyze_multiple_sentences(texts)

"""Visualize Sentiment Distribution"""

import matplotlib.pyplot as plt

def visualize_sentiment(texts):
    results = sentiment_pipeline(texts)
    sentiments = [result['label'] for result in results]

    # Count the sentiments
    from collections import Counter
    sentiment_counts = Counter(sentiments)

    # Plot the results
    plt.bar(sentiment_counts.keys(), sentiment_counts.values())
    plt.title("Sentiment Distribution")
    plt.xlabel("Sentiment")
    plt.ylabel("Count")
    plt.show()

texts = [
    "I love this project!",
    "This is the worst experience ever.",
    "It's okay, not great.",
    "Absolutely fantastic!",
    "I'm feeling neutral about this."
]
visualize_sentiment(texts)

# using pre-trained model

sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

!pip install transformers torch

from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Creating a function for sentiment analysis
def analyze_sentiment(text):
    if text.strip() == "":
        return "Please enter some text to analyze!"

    # Perform sentiment analysis
    result = sentiment_pipeline(text)[0]
    sentiment = result['label']
    confidence = result['score']

    return f"Sentiment: {sentiment}\nConfidence: {confidence:.2f}"

# Get user input and display results
user_input = input("Enter some text to analyze: ")
result = analyze_sentiment(user_input)
print(result)

